# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_Widget(object):
    def setupUi(self, edit_Widget):
        edit_Widget.setObjectName("edit_Widget")
        edit_Widget.resize(200, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(edit_Widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(edit_Widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.editJsonTextBrowser = QtWidgets.QTextBrowser(edit_Widget)
        self.editJsonTextBrowser.setObjectName("editJsonTextBrowser")
        self.verticalLayout.addWidget(self.editJsonTextBrowser)
        self.editCleanTextButton = QtWidgets.QPushButton(edit_Widget)
        self.editCleanTextButton.setObjectName("editCleanTextButton")
        self.verticalLayout.addWidget(self.editCleanTextButton)
        self.line = QtWidgets.QFrame(edit_Widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.editExportButton = QtWidgets.QPushButton(edit_Widget)
        self.editExportButton.setObjectName("editExportButton")
        self.verticalLayout.addWidget(self.editExportButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(edit_Widget)
        QtCore.QMetaObject.connectSlotsByName(edit_Widget)

    def retranslateUi(self, edit_Widget):
        _translate = QtCore.QCoreApplication.translate
        edit_Widget.setWindowTitle(_translate("edit_Widget", "edit"))
        self.label.setText(_translate("edit_Widget", "Areas Info. (JSON)"))
        self.editCleanTextButton.setText(_translate("edit_Widget", "Clean"))
        self.editExportButton.setText(_translate("edit_Widget", "ExportToJSONFile"))
