# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/frontend/UI/mainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(200, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainPushButton1 = QtWidgets.QPushButton(mainWidget)
        self.mainPushButton1.setObjectName("mainPushButton1")
        self.verticalLayout.addWidget(self.mainPushButton1)
        self.mainPushButton2 = QtWidgets.QPushButton(mainWidget)
        self.mainPushButton2.setObjectName("mainPushButton2")
        self.verticalLayout.addWidget(self.mainPushButton2)
        self.mainPushButton3 = QtWidgets.QPushButton(mainWidget)
        self.mainPushButton3.setObjectName("mainPushButton3")
        self.verticalLayout.addWidget(self.mainPushButton3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "mainWidget"))
        self.mainPushButton1.setText(_translate("mainWidget", "mainBtn1"))
        self.mainPushButton2.setText(_translate("mainWidget", "mainBtn2"))
        self.mainPushButton3.setText(_translate("mainWidget", "mainBtn3"))
