# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim_subWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Simulation_Window(object):
    def setupUi(self, Simulation_Window):
        Simulation_Window.setObjectName("Simulation_Window")
        Simulation_Window.resize(720, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Simulation_Window.sizePolicy().hasHeightForWidth())
        Simulation_Window.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Simulation_Window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(Simulation_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webEngineView.sizePolicy().hasHeightForWidth())
        self.webEngineView.setSizePolicy(sizePolicy)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.horizontalLayout.addWidget(self.webEngineView)

        self.retranslateUi(Simulation_Window)
        QtCore.QMetaObject.connectSlotsByName(Simulation_Window)

    def retranslateUi(self, Simulation_Window):
        _translate = QtCore.QCoreApplication.translate
        Simulation_Window.setWindowTitle(_translate("Simulation_Window", "Simulation"))
from PyQt5 import QtWebEngineWidgets
